# This file is used to configure
# the application properties for the development environment.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-falling-sun-a1d9wda6.ap-southeast-1.aws.neon.tech/ecommerce010702?sslmode=require
    username: ecommerce010702_owner
    password: mtHkzhY9A3PQ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'