# This file is used to configure
# the application properties for the development environment.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-shrill-truth-a1tzyu0n.ap-southeast-1.aws.neon.tech/ecommerce010702?sslmode=require
    username: cosmeticweb0702_owner
    password: weUa5Ep1hVzc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'